name: Terraform Validator
on:
  pull_request:
    branches:
      - development
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code in the pipeline
        uses: actions/checkout@v2

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -json